const { jsPDF } = window.jspdf;

function generatePDF(){

    const { jsPDF } = window.jspdf;

    const doc = new jsPDF();

    const personName =
        document.getElementById("name").value.trim() || "FORMat Lite";

    doc.setFont("helvetica","bold");
    doc.setFontSize(20);
    doc.text(personName.toUpperCase(),20,20);

    doc.setLineWidth(0.5);
    doc.line(20,25,190,25);

    /* Photo Placeholder */

doc.rect(155,30,35,45);

doc.setFontSize(10);
doc.text("PHOTO",166,55);

/* Start details below the heading */

let y = 40;

    const fields=[

        ["Full Name","name"],
        ["Father's Name","father"],
        ["Age","age"],
        ["Date of Birth","dob"],
        ["Gender","gender"],
        ["Mobile Number","mobile"],
        ["Email","email"],
        ["Blood Group","blood"],
        ["Nationality","nationality"],
        ["Marital Status","marital"],
        ["Occupation","occupation"],
        ["Address","address"]

    ];

    doc.setFontSize(11);

    fields.forEach(function(f){

        const value=document.getElementById(f[1]).value || "";

        doc.setFont("helvetica","bold");
        doc.text(f[0],20,y);

        doc.setFont("helvetica","normal");
        doc.text(": "+value,70,y);

        y+=10;

    });

    doc.line(20,y+5,190,y+5);

    doc.setFontSize(9);

    doc.text(
        "Generated by FORMat Lite",
        20,
        y+15
    );

    const fileName =
        personName.replace(/[^a-zA-Z0-9]/g,"_") || "FORMat_Lite";

    doc.save(fileName + ".pdf");

}
